module.exports = (sequelize, DataTypes) => {
    const Loading_Program = sequelize.define("Loading_Program", {
        localCustom:      { type:DataTypes.STRING },
        wharf:            { type:DataTypes.STRING },
        loadingTerminal:  { type:DataTypes.STRING },
        dischargeTerminal:{ type:DataTypes.STRING },
        loadingDate:      { type:DataTypes.STRING },
        loadingTime:      { type:DataTypes.STRING },
        arrivalDate:      { type:DataTypes.STRING },
        croIssueDate:     { type:DataTypes.STRING },
        expiryDate:       { type:DataTypes.STRING },
        egm:              { type:DataTypes.STRING },
        etd:              { type:DataTypes.STRING },
        book:             { type:DataTypes.STRING },
        gatePass:         { type:DataTypes.STRING },
        gatePassDate:     { type:DataTypes.STRING },
        letter:           { type:DataTypes.STRING },
        cro:              { type:DataTypes.STRING },
        validityDate:     { type:DataTypes.STRING },
        berth:            { type:DataTypes.STRING },
        viaPort:          { type:DataTypes.STRING },
        containerInfo:    { type:DataTypes.STRING },
        portOfReciept:    { type:DataTypes.STRING },
        portOfReciept:    { type:DataTypes.STRING },
        instruction:      { type:DataTypes.TEXT('long')},
        loadingFlag:      { type:DataTypes.STRING },
        status:           { type:DataTypes.STRING },
        allocAvailable:   { type:DataTypes.STRING },
        contAvailable:    { type:DataTypes.STRING },
        sobDate:          { type:DataTypes.STRING },
        containerSplit:   { type:DataTypes.STRING },
        blRequired:       { type:DataTypes.STRING },
        containerWt:      { type:DataTypes.STRING },
        containerPickup:  { type:DataTypes.STRING },
        containerTemp:    { type:DataTypes.STRING },
        vent:             { type:DataTypes.STRING },
        loadingTerms:     { type:DataTypes.TEXT('long')}
    })
    return Loading_Program;
}